## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Приглашение"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = ""
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  telegram = "https://telegram.org"